using System.Runtime.InteropServices;

namespace AvaloniaInside.MediaPlayer.FFmpeg;

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct AVFormatContext
{
    public IntPtr av_class;
    public IntPtr iformat;
    public IntPtr oformat;
    public IntPtr priv_data;
    public IntPtr pb;
    public int ctx_flags;
    public uint nb_streams;
    public AVStream** streams;
    public IntPtr url;
    public long start_time;
    public long duration;
    public long bit_rate;
    public uint packet_size;
    public int max_delay;
    public int flags;
    public long probesize;
    public long max_analyze_duration;
    public IntPtr key;
    public int keylen;
    public uint nb_programs;
    public AVProgram** programs;
    public AVCodecID video_codec_id;
    public AVCodecID audio_codec_id;
    public AVCodecID subtitle_codec_id;
    public uint max_index_size;
    public uint max_picture_buffer;
    public uint nb_chapters;
    public AVChapter** chapters;
    public IntPtr metadata;
    public long start_time_realtime;
    public int fps_probe_size;
    public int error_recognition;
    public AVIOInterruptCB interrupt_callback;
    public int debug;
    public long max_interleave_delta;
    public int strict_std_compliance;
    public int event_flags;
    public int max_ts_probe;
    public int avoid_negative_ts;
    public int ts_id;
    public int audio_preload;
    public int max_chunk_duration;
    public int max_chunk_size;
    public int use_wallclock_as_timestamps;
    public int avio_flags;
    public AVDurationEstimationMethod duration_estimation_method;
    public long skip_initial_bytes;
    public uint correct_ts_overflow;
    public int seek2any;
    public int flush_packets;
    public int probe_score;
    public int format_probesize;
    public IntPtr codec_whitelist;
    public IntPtr format_whitelist;
    public int io_repositioned;
    public IntPtr video_codec;
    public IntPtr audio_codec;
    public IntPtr subtitle_codec;
    public IntPtr data_codec;
    public int metadata_header_padding;
    public IntPtr opaque;
    public IntPtr control_message_cb;
    public long output_ts_offset;
    public IntPtr dump_separator;
    public AVCodecID data_codec_id;
    public IntPtr protocol_whitelist;
    public IntPtr io_open;
    public IntPtr protocol_blacklist;
    public int max_streams;
    public int skip_estimate_duration_from_pts;
    public int max_probe_packets;
    public IntPtr io_close2;
}